# Generated by Django 6.0.1 on 2026-03-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
                ('foto_perfil_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('boleta_pdf', models.FileField(blank=True, null=True, upload_to='boletas/')),
            ],
        ),
    ]
