# Generated by Django 6.0.2 on 2026-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
            ],
        ),
    ]
