# Generated by Django 6.0.1 on 2026-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
