# Generated by Django 6.0.1 on 2026-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='boleta_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
