# Generated by Django 6.0.1 on 2026-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_boleta_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
